version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data_container: